/*
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "nearlink_dft_database.h"
#include <string>

static HiSysEventParamType g_dtToHt[DFT_TYPE_BUTT] = {
    HISYSEVENT_INVALID,                                 // DFT_PARAM_TYPE_INVALID
    HISYSEVENT_BOOL,
    HISYSEVENT_UINT8,
    HISYSEVENT_INT8,
    HISYSEVENT_UINT16,
    HISYSEVENT_INT16,
    HISYSEVENT_UINT32,
    HISYSEVENT_INT32,
    HISYSEVENT_STRING,
    HISYSEVENT_STRING,
};

/*******************************************************************************
 *  detail exception event param define below. Note that the sequence is the same as that of Excep Event param index
 ******************************************************************************/
static DftParamDB g_templateOneExcepParam[EXCEP_TEMPLATE_ONE_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // EXCEP_TEMPLATE_ONE_INVALID
    {"", HISYSEVENT_INVALID},                           // EXCEP_TEMPLATE_ONE_KEY_BUTT
    {"ERROR_CODE", HISYSEVENT_INT32},
    {"SUB_ERROR_CODE", HISYSEVENT_INT32},
    {"TIME_STAMP", HISYSEVENT_STRING},
};

static DftParamDB g_templateThreeExcepParam[EXCEP_TEMPLATE_THREE_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // EXCEP_TEMPLATE_THREE_INVALID
    {"", HISYSEVENT_INVALID},                           // EXCEP_TEMPLATE_THREE_KEY_BUTT
    {"PEER_INFO", HISYSEVENT_STRING},
    {"ERROR_CODE", HISYSEVENT_INT32},
    {"SUB_ERROR_CODE", HISYSEVENT_INT32},
    {"TIME_STAMP", HISYSEVENT_STRING},
};

static DftParamDB g_audioStreamExcepParam[STREAM_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // STREAM_INVALID
    {"STREAM_DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // STREAM_KEY_BUTT
    {"STREAM_DEVICE_NAME", HISYSEVENT_STRING},
    {"STREAM_DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"STREAM_REPORT_ADDR", HISYSEVENT_STRING},
    {"STREAM_OPERATION_TYPE", HISYSEVENT_UINT16},
    {"STREAM_RUNNING_TYPE", HISYSEVENT_UINT8},
    {"STREAM_ASC_STATE", HISYSEVENT_INT32},
    {"STREAM_START_BUFF_TYPE", HISYSEVENT_STRING},
    {"STREAM_JUDGE_RECONFIG", HISYSEVENT_UINT16},
    {"STREAM_CONFIG_PARAM", HISYSEVENT_STRING},
    {"STREAM_CONFIGURING_TIME", HISYSEVENT_STRING},
    {"STREAM_OPENING_TIME", HISYSEVENT_STRING},
    {"STREAM_STARTING_TIME", HISYSEVENT_STRING},
    {"STREAM_STOPPING_TIME", HISYSEVENT_STRING},
    {"STREAM_RELEASING_TIME", HISYSEVENT_STRING},
    {"STREAM_RESULT_TIME", HISYSEVENT_STRING},
    {"STREAM_POINT_TYPE", HISYSEVENT_UINT8},
    {"STREAM_OPERATOR_RESULT", HISYSEVENT_UINT8},
    {"STREAM_OPERATOR_ERROR_CODE", HISYSEVENT_INT32},
};

static DftParamDB g_switchExcepParam[SWITCH_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // SWITCH_INVALID
    {"", HISYSEVENT_INVALID},                           // SWITCH_KEY_BUTT
    {"SWITCH_TYPE_INFO", HISYSEVENT_UINT16},
    {"SWITCH_OPER_RES", HISYSEVENT_UINT16},
    {"SWITCH_ERR_CODE", HISYSEVENT_UINT16},
    {"SWITCH_INFO_MSG", HISYSEVENT_STRING},
    {"SWITCH_USED_APP", HISYSEVENT_STRING},
    {"SWITCH_START_TIME", HISYSEVENT_STRING},
    {"SWITCH_END_TIME", HISYSEVENT_STRING},
    {"SUB_STATE_FLOW", HISYSEVENT_STRING},
};

static DftParamDB g_disconnExcepParam[DISCONN_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // DISCONN_INVALID
    {"DISCONN_PEER_ADDR", HISYSEVENT_STRING},
    {"DISCONN_PEER_TYPE", HISYSEVENT_UINT16},
    {"", HISYSEVENT_INVALID},                           // DISCONN_KEY_BUTT
    {"DISCONN_SCENE", HISYSEVENT_UINT16},
    {"DISCONN_ERRORCODE", HISYSEVENT_INT32},
    {"DISCONN_INFO_MSG", HISYSEVENT_STRING},
    {"DISCONN_TIME", HISYSEVENT_STRING},
    {"DISCONN_DEVICE_RSSI", HISYSEVENT_INT32},
    {"SUB_PEER_INFO", HISYSEVENT_STRING},
    {"SUB_CONN_INFO", HISYSEVENT_STRING},
};

static DftParamDB g_accuratesearchExcepParam[ACCURATESEARCH_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // ACCURATESEARCH_INVALID
    {"PEER_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // ACCURATESEARCH_KEY_BUTT
    {"PATH", HISYSEVENT_UINT16},
    {"CONN_RESULT", HISYSEVENT_UINT16},
    {"CONN_FAIL_ERROR_CODE", HISYSEVENT_INT32},
    {"MEASURE_RESULT", HISYSEVENT_UINT16},
    {"MEASURE_FAIL_ERROR_CODE", HISYSEVENT_INT32},
    {"MEASURE_START_TIME", HISYSEVENT_STRING},
    {"MEASURE_END_TIME", HISYSEVENT_STRING},
    {"DISCONN_ERROR_CODE", HISYSEVENT_INT32},
    {"RSSI_VALUE", HISYSEVENT_INT32},
};

static DftParamDB g_pairInfoParam[PAIR_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // PAIR_INVALID
    {"SLE_DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // PAIR_KEY_BUTT
    {"SLE_DEVICE_TYPE", HISYSEVENT_UINT16},
    {"SLE_DEVICE_NAME", HISYSEVENT_STRING},
    {"SLE_APP_NAME", HISYSEVENT_STRING},
    {"SLE_PAIR_PROCESS_TYPE", HISYSEVENT_STRING},
    {"SLE_CONN_PATH", HISYSEVENT_UINT16},
    {"SLE_ACB_START_TIME", HISYSEVENT_STRING},
    {"SLE_ACB_FINISH_TIME", HISYSEVENT_STRING},
    {"SLE_PAIR_START_TIME", HISYSEVENT_STRING},
    {"SLE_PAIR_FINISH_TIME", HISYSEVENT_STRING},
    {"SLE_SSAP_START_TIME", HISYSEVENT_STRING},
    {"SLE_SSAP_FINISH_TIME", HISYSEVENT_STRING},
    {"SLE_DIS_START_TIME", HISYSEVENT_STRING},
    {"SLE_DIS_FINISH_TIME", HISYSEVENT_STRING},
    {"SLE_HID_START_TIME", HISYSEVENT_STRING},
    {"SLE_HID_FINISH_TIME", HISYSEVENT_STRING},
    {"SLE_ICCE_START_TIME", HISYSEVENT_STRING},
    {"SLE_ICCE_FINISH_TIME", HISYSEVENT_STRING},
    {"SLE_POFILE_START_TIME", HISYSEVENT_STRING},
    {"SLE_PROFILE_FINISH_TIME", HISYSEVENT_STRING},
    {"SLE_CONN_ERROR_CODE", HISYSEVENT_INT32},
    {"SLE_CONN_DEV_COUNT", HISYSEVENT_UINT16},
    {"SLE_PAIR_TYPE", HISYSEVENT_UINT16},
    {"SLE_CONN_TYPE", HISYSEVENT_UINT16},
    {"SLE_CONN_RESULT", HISYSEVENT_UINT16},
    {"SLE_PAIR_RESULT", HISYSEVENT_UINT16},
    {"SLE_CONN_ERROR_REASON", HISYSEVENT_STRING},
    {"SLE_DISCON_RSSI", HISYSEVENT_INT32},
    {"SLE_NOISE_VALUE", HISYSEVENT_STRING},
    {"REPORT_ADDR", HISYSEVENT_STRING},
    {"NUMBER_OF_MEMBERS", HISYSEVENT_UINT16},
    {"ADDR_OF_MEMBERS", HISYSEVENT_STRING},
};

static DftParamDB g_unpairInfoParam[UNPAIR_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // UNPAIR_INVALID
    {"UNPAIR_DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // UNPAIR_KEY_BUTT
    {"UNPAIR_DEVICE_TYPE", HISYSEVENT_UINT16},
    {"UNPAIR_APP_NAME", HISYSEVENT_STRING},
    {"UNPAIR_CONSTATE", HISYSEVENT_UINT16},
    {"UNPAIR_SCENE", HISYSEVENT_UINT16},
    {"UNPAIR_DELETEKEY_RESULT", HISYSEVENT_UINT16},
    {"UNPAIR_DELETEKEY_TIME", HISYSEVENT_STRING},
    {"UNPAIR_RESULT", HISYSEVENT_UINT16},
    {"UNPAIR_ERRORCODE", HISYSEVENT_INT32},
    {"UNPAIR_START_TIME", HISYSEVENT_STRING},
    {"UNPAIR_END_TIME", HISYSEVENT_STRING},
};

static DftParamDB g_multideviceconnParam[MULTIDEVICECONN_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // MULTIDEVICECONN_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // MULTIDEVICECONN_KEY_BUTT
    {"CONN_MODULE_NAME", HISYSEVENT_STRING},
    {"DEVICE_CONN_STATE", HISYSEVENT_UINT16},
    {"DEVICE_SERVICE_STATE", HISYSEVENT_UINT16},
    {"DEVICE_CONN_LAST_TIME", HISYSEVENT_STRING},
    {"DEVICE_DISCONN_LAST_TIME", HISYSEVENT_STRING},
    {"DEVICE_UPDATE_TIME", HISYSEVENT_STRING},
};

static DftParamDB g_disExposedExcepParam[EXCEP_TEMPLATE_TWO_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // EXCEP_TEMPLATE_TWO_INVALID
    {"", HISYSEVENT_INVALID},                           // EXCEP_TEMPLATE_TWO_KEY_BUTT
    {"ERROR_CODE", HISYSEVENT_INT32},
    {"SUB_ERROR_CODE", HISYSEVENT_INT32},
    {"SLE_DEVICE_NAME", HISYSEVENT_STRING},
};

static DftParamDB g_icceProfileExcepParam[ICCE_PROFILE_EXCEP_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_SEVEN_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_SEVEN_KEY_BUTT
    {"DEVICE_NAME", HISYSEVENT_STRING},
    {"DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"ERROR_CODE", HISYSEVENT_INT32},
    {"SUB_ERROR_CODE", HISYSEVENT_INT32},
};

static DftParamDB g_audioProfileExcepParam[AUDIO_PROFILE_EXCEP_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_SEVEN_INVALID
    {"PROFILE_DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_SEVEN_KEY_BUTT
    {"PROFILE_DEVICE_NAME", HISYSEVENT_STRING},
    {"PROFILE_DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"PROFILE_ERROR_CODE", HISYSEVENT_UINT16},
    {"PROFILE_SUB_ERROR_CODE", HISYSEVENT_UINT16},
    {"PROFILE_EXTRA_PARAM", HISYSEVENT_STRING},
};

static DftParamDB g_stackSmGNegoExcepParam[SM_G_NEGO_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // SM_G_NEGO_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // SM_G_NEGO_KEY_BUTT
    {"PEER_INFO", HISYSEVENT_STRING},
    {"START_PAIR_TIME", HISYSEVENT_STRING},
    {"GEN_KEY_TIME", HISYSEVENT_STRING},
    {"RECV_PAIR_START_TIME", HISYSEVENT_STRING},
    {"SEND_PAIR_REQ_TIME", HISYSEVENT_STRING},
    {"RECV_PAIR_RESP_TIME", HISYSEVENT_STRING},
    {"SEND_PAIR_CFM_TIME", HISYSEVENT_STRING},
    {"RECV_PAIR_INIT_TIME", HISYSEVENT_STRING},
    {"ERR_CODE", HISYSEVENT_UINT16},
    {"NEGO_RES", HISYSEVENT_UINT16}
};

static DftParamDB g_stackSmTNegoExcepParam[SM_T_NEGO_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // SM_T_NEGO_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // SM_T_NEGO_KEY_BUTT
    {"PEER_INFO", HISYSEVENT_STRING},
    {"START_PAIR_TIME", HISYSEVENT_STRING},
    {"GEN_KEY_TIME", HISYSEVENT_STRING},
    {"SEND_PAIR_START_TIME", HISYSEVENT_STRING},
    {"RECV_PAIR_REQ_TIME", HISYSEVENT_STRING},
    {"SEND_PAIR_RESP_TIME", HISYSEVENT_STRING},
    {"RECV_PAIR_CFM_TIME", HISYSEVENT_STRING},
    {"SEND_PAIR_INIT_TIME", HISYSEVENT_STRING},
    {"ERR_CODE", HISYSEVENT_UINT16},
    {"NEGO_RES", HISYSEVENT_UINT16}
};

static DftParamDB g_stackSmGAuthExcepParam[SM_G_AUTH_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // SM_G_AUTH_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // SM_G_AUTH_KEY_BUTT
    {"PEER_INFO", HISYSEVENT_STRING},
    {"AUTH_METHOD", HISYSEVENT_UINT16},
    {"GEN_PASSCODE_TIME", HISYSEVENT_STRING},
    {"RECV_CFM_TIME", HISYSEVENT_STRING},
    {"SEND_RA_TIME", HISYSEVENT_STRING},
    {"RECV_RB_TIME", HISYSEVENT_STRING},
    {"USER_CFM_TIME", HISYSEVENT_STRING},
    {"GEN_KEY_TIME", HISYSEVENT_STRING},
    {"GEN_CFMKEY_TIME", HISYSEVENT_STRING},
    {"SEND_CFMKEY_TIME", HISYSEVENT_STRING},
    {"RECV_CFMKEY_TIME", HISYSEVENT_STRING},
    {"ERR_CODE", HISYSEVENT_UINT16},
    {"AUTH_RES", HISYSEVENT_UINT16}
};

static DftParamDB g_stackSmTAuthExcepParam[SM_T_AUTH_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // SM_T_AUTH_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // SM_T_AUTH_KEY_BUTT
    {"PEER_INFO", HISYSEVENT_STRING},
    {"AUTH_METHOD", HISYSEVENT_UINT16},
    {"GEN_CFM_TIME", HISYSEVENT_STRING},
    {"RECV_CFM_TIME", HISYSEVENT_STRING},
    {"RECV_RA_TIME", HISYSEVENT_STRING},
    {"SEND_CFM_TIME", HISYSEVENT_STRING},
    {"SEND_RB_TIME", HISYSEVENT_STRING},
    {"USER_CFM_TIME", HISYSEVENT_STRING},
    {"GEN_KEY_TIME", HISYSEVENT_STRING},
    {"GEN_CFMKEY_TIME", HISYSEVENT_STRING},
    {"SEND_CFMKEY_TIME", HISYSEVENT_STRING},
    {"RECV_CFMKEY_TIME", HISYSEVENT_STRING},
    {"ERR_CODE", HISYSEVENT_UINT16},
    {"AUTH_RES", HISYSEVENT_UINT16}
};

static DftParamDB g_stackSmEncpExcepParam[SM_ENCP_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // SM_ENCP_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // SM_ENCP_KEY_BUTT
    {"PEER_INFO", HISYSEVENT_STRING},
    {"ENABLE_TIME", HISYSEVENT_STRING},
    {"REQ_PARAM_TIME", HISYSEVENT_STRING},
    {"ERR_CODE", HISYSEVENT_UINT16},
    {"ENCP_RES", HISYSEVENT_UINT16}
};

static DftParamDB g_datatransferConnParam[DATATRANSFERCONN_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // DATATRANSFERCONN_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // DATATRANSFERCONN_KEY_BUTT
    {"TIMESTAMP", HISYSEVENT_STRING},
    {"DEVICE_NAME", HISYSEVENT_STRING},
    {"DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"CALLING_NAME", HISYSEVENT_STRING},
    {"SCENE_CODE", HISYSEVENT_INT32},
    {"SUB_SCENE_CODE", HISYSEVENT_INT32},
};

static DftParamDB g_datatransferExcepParam[DATATRANSFEREXCEP_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},  // DATATRANSFEREXCEP_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},  // DATATRANSFEREXCEP_KEY_BUTT
    {"TIMESTAMP", HISYSEVENT_STRING},
    {"DEVICE_NAME", HISYSEVENT_STRING},
    {"DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"CALLING_NAME", HISYSEVENT_STRING},
    {"TYPE", HISYSEVENT_INT32},
    {"ERROR_CODE", HISYSEVENT_INT32},
    {"SUB_ERROR_CODE", HISYSEVENT_INT32},
};

static DftParamDB g_audioHeadsetExcepParam[AUDIO_HEADSET_EXCEP_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},  // AUDIO_HEADSET_EXCEP_INVALID
    {"AUDIO_DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},  // AUDIO_HEADSET_EXCEP_KEY_BUTT
    {"AUDIO_DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"AUDIO_DEVICE_NAME", HISYSEVENT_STRING},
    {"FREQ_BAND", HISYSEVENT_UINT16},
    {"AUDIO_SCENE_CODE", HISYSEVENT_UINT16},
    {"USER_SCENE_CODE", HISYSEVENT_UINT16},
    {"ERROR_CODE", HISYSEVENT_UINT16},
    {"AUDIO_SOURCE_RSSI", HISYSEVENT_INT32},
    {"OTHER_EAR_RSSI", HISYSEVENT_INT32},
    {"WRONG_PACKAGE_RATE", HISYSEVENT_UINT16},
    {"MISORDER_CNT_RXSEQ", HISYSEVENT_UINT16},
    {"NOSYNC_RATE", HISYSEVENT_UINT16},
    {"LNA_SWITCH", HISYSEVENT_UINT16},
    {"DOUBLE_TUNED_STATE", HISYSEVENT_UINT16},
    {"CODEC_TYPE", HISYSEVENT_UINT16},
    {"BITRATE_INFO", HISYSEVENT_UINT16},
    {"DEVICE_NUM_IN_LINK", HISYSEVENT_UINT16},
    {"STRONG_CHANNEL_NUM", HISYSEVENT_UINT16},
    {"MID_CHANNEL_NUM", HISYSEVENT_UINT16},
    {"WEAK_CHANNEL_NUM", HISYSEVENT_UINT16},
    {"NOISE_AVG_VALUE", HISYSEVENT_INT32},
};

/*******************************************************************************
 *  detail ue event param define below.Note that the sequence is the same as that of UE Event param index
 ******************************************************************************/
static DftParamDB g_templateOneUeParam[UE_TEMPLATE_ONE_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_ONE_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_ONE_KEY_BUTT
    {"DEVICE_NAME", HISYSEVENT_STRING},
    {"DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"SCENE_CODE", HISYSEVENT_INT32},
    {"SUB_SCENE_CODE", HISYSEVENT_INT32},
    {"TIME_STAMP", HISYSEVENT_STRING},
};

static DftParamDB g_templateTwoUeParam[UE_TEMPLATE_TWO_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_TWO_INVALID
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_TWO_KEY_BUTT
    {"DEVICE_NAME", HISYSEVENT_STRING},
    {"DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"SCENE_CODE", HISYSEVENT_INT32},
    {"SUB_SCENE_CODE", HISYSEVENT_INT32},
    {"CALLING_NAME", HISYSEVENT_STRING},
    {"TIME_STAMP", HISYSEVENT_STRING},
};

static DftParamDB g_disExposedUeParam[UE_TEMPLATE_SEVEN_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_SEVEN_INVALID
    {"", HISYSEVENT_INVALID},                           // UE_TEMPLATE_SEVEN_KEY_BUTT
    {"SCENE_CODE", HISYSEVENT_INT32},
    {"SUB_SCENE_CODE", HISYSEVENT_INT32},
    {"SLE_DEVICE_NAME", HISYSEVENT_STRING},
};

static DftParamDB g_measureStateUeParam[MEASURE_STATE_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // MEASURE_STATE_INVALID
    {"", HISYSEVENT_INVALID},                           // MEASURE_STATE_KEY_BUTT
    {"INDEX", HISYSEVENT_INT32},
    {"SCENE_CODE", HISYSEVENT_INT32},
    {"SUB_SCENE_CODE", HISYSEVENT_INT32},
};

static DftParamDB g_audioSinkDeviceUeParam[AUDIO_SINK_DEVICE_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // AUDIO_SINK_DEVICE_INVALID
    {"", HISYSEVENT_INVALID},                           // AUDIO_SINK_DEVICE_KEY_BUTT
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"DEVICE_NAME", HISYSEVENT_STRING},
    {"DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"SCENE_CODE", HISYSEVENT_INT32},
    {"SUB_SCENE_CODE", HISYSEVENT_INT32},
    {"CHANGE_REASON", HISYSEVENT_UINT16},
    {"TIME_STAMP", HISYSEVENT_STRING},
};

static DftParamDB g_audioSourceDeviceUeParam[AUDIO_SOURCE_DEVICE_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // AUDIO_SOURCE_DEVICE_INVALID
    {"", HISYSEVENT_INVALID},                           // AUDIO_SOURCE_DEVICE_KEY_BUTT
    {"CURRENT_DEVICE_ADDR", HISYSEVENT_STRING},
    {"CURRENT_DEVICE_NAME", HISYSEVENT_STRING},
    {"CURRENT_DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"OLD_DEVICE_ADDR", HISYSEVENT_STRING},
    {"OLD_DEVICE_NAME", HISYSEVENT_STRING},
    {"OLD_DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"SCENE_CODE", HISYSEVENT_INT32},
    {"SUB_SCENE_CODE", HISYSEVENT_INT32},
    {"TIME_STAMP", HISYSEVENT_STRING},
};

static DftParamDB g_audioMuteStreamUeParam[AUDIO_MUTE_STREAM_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // AUDIO_MUTE_STREAM_INVALID
    {"", HISYSEVENT_INVALID},                           // AUDIO_MUTE_STREAM_KEY_BUTT
    {"DEVICE_ADDR", HISYSEVENT_STRING},
    {"DEVICE_NAME", HISYSEVENT_STRING},
    {"DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"SCENE_CODE", HISYSEVENT_INT32},
    {"SUB_SCENE_CODE", HISYSEVENT_INT32},
    {"MUTE_CHECK_TIME", HISYSEVENT_INT32},
    {"DEBOUNCE_TIME", HISYSEVENT_INT32},
    {"APP_NAME", HISYSEVENT_STRING},
};

/*******************************************************************************
 *  detail sub event param define below.Note that the sequence is the same as that of sub Event param index
 ******************************************************************************/

static DftParamDB g_stateFlowParam[STATE_FLOW_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // STATE_FLOW_INFO_INVALID
    {"", HISYSEVENT_INVALID},                           // STATE_FLOW_KEY_BUTT
    {"STATE_FLOW", HISYSEVENT_STRING},
};

static DftParamDB g_peerInfoParam[PEER_INFO_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // PEER_INFO_INVALID
    {"PEER_ADDR", HISYSEVENT_STRING},
    {"PEER_TYPE", HISYSEVENT_UINT16},
    {"", HISYSEVENT_INVALID},                           // PEER_INFO_KEY_BUTT
    {"PEER_INFO_NAME", HISYSEVENT_STRING},
    {"PEER_CONN_LAST_TIME", HISYSEVENT_STRING},
    {"PEER_HID_STATE", HISYSEVENT_UINT16},
    {"PEER_HID_CONN_TIME", HISYSEVENT_STRING},
    {"PEER_DEVICE_APPEARANCE", HISYSEVENT_INT32},
    {"PEER_DEVICE_MANUFACTURER", HISYSEVENT_STRING},
};

static DftParamDB g_connInfoParam[CONN_INFO_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // CONN_INFO_INVALID
    {"CONN_INFO_ADDR", HISYSEVENT_STRING},
    {"CONN_INFO_TYPE", HISYSEVENT_UINT16},
    {"", HISYSEVENT_INVALID},                           // CONN_INFO_KEY_BUTT
    {"UP_CONN_REQ_TIME", HISYSEVENT_STRING},
    {"LAST_CONN_REQ_TIME", HISYSEVENT_STRING},
    {"CONN_COMP_TIME", HISYSEVENT_STRING},
    {"UP_DISCONN_REQ_TIME", HISYSEVENT_STRING},
    {"DISCONN_COMP_TIME", HISYSEVENT_STRING},
    {"AUTH_COMP_TIME", HISYSEVENT_STRING},
    {"ENCRY_COMP_TIME", HISYSEVENT_STRING},
    {"HID_COMP_TIME", HISYSEVENT_STRING},
};

static DftParamDB g_audioCodecExcepParam[NL_DFT_CODEC_EXCEP_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // NL_DFT_CODEC_EXCEP_INVALID
    {"", HISYSEVENT_INVALID},                           // NL_DFT_CODEC_EXCEP_KEY_BUTT
    {"TIME", HISYSEVENT_STRING},
    {"CODEC_TYPE", HISYSEVENT_UINT8},
    {"CODEC_ALGO", HISYSEVENT_UINT8},
    {"ERROR_CODE", HISYSEVENT_INT32},
};

static DftParamDB g_audioChoppyExcepParam[NL_DFT_CHOPPY_EXCEP_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // NL_DFT_CODEC_EXCEP_INVALID
    {"", HISYSEVENT_INVALID},                           // NL_DFT_CODEC_EXCEP_KEY_BUTT
    {"TIME", HISYSEVENT_STRING},
    {"CHOPPY_CNT", HISYSEVENT_UINT8},
    {"DSP_DEVICE_ADDR", HISYSEVENT_STRING},
    {"DSP_DEVICE_TYPE", HISYSEVENT_INT32},
    {"DSP_DEVICE_NAME", HISYSEVENT_STRING},
    {"DSP_REPORT_ADDR", HISYSEVENT_STRING},
    {"DSP_SCENE_CODE", HISYSEVENT_UINT32},
    {"DSP_SUBSCENE_CODE", HISYSEVENT_UINT32},
    {"DSP_BITRATE_INFO", HISYSEVENT_UINT32},
    {"DSP_CONFIG_PARAM", HISYSEVENT_STRING},
    {"DSP_FREQ_BAND", HISYSEVENT_UINT32},
    {"DSP_POWER_INFO", HISYSEVENT_UINT32},
    {"DSP_MAC_INFO", HISYSEVENT_UINT32},
    {"DSP_PEER_RSSI", HISYSEVENT_INT32},
    {"DSP_TXFLUSH_NUM", HISYSEVENT_UINT32},
    {"DSP_ACK_RATE", HISYSEVENT_UINT32},
    {"DSP_CHANNEL_STATUS_24G", HISYSEVENT_STRING},
    {"DSP_NOISE_AVG_VALUE_24G", HISYSEVENT_INT32},
    {"DSP_CHANNEL_STATUS_5G", HISYSEVENT_STRING},
    {"DSP_NOISE_AVG_VALUE_5G", HISYSEVENT_INT32},
};

static DftParamDB g_audioStatsParam[NL_DFT_STATS_PARAM_BUTT] = {
    {"", HISYSEVENT_INVALID},                           // NL_DFT_STATS_INVALID
    {"", HISYSEVENT_INVALID},                           // NL_DFT_STATS_KEY_BUTT
    {"START_TIME", HISYSEVENT_STRING},
    {"DURATION", HISYSEVENT_UINT32},
    {"L2HC_VERSION", HISYSEVENT_UINT8},
    {"CODEC_TYPE", HISYSEVENT_UINT8},
    {"SAMPLE_RATE", HISYSEVENT_UINT8},
    {"BITDEPTH", HISYSEVENT_UINT8},
    {"CHANNEL_MODE", HISYSEVENT_UINT8},
    {"DEVICE_NUM_IN_COOPERATION_SET", HISYSEVENT_UINT8},
    {"SDU_INTERVAL", HISYSEVENT_UINT8},
    {"FLUSH_TIMEOUT", HISYSEVENT_UINT8},
    {"BURST_NUM", HISYSEVENT_UINT8},
    {"MAX_DOWN_BITRATE", HISYSEVENT_UINT16},
    {"MAX_DOWN_BITRATE_DURATION", HISYSEVENT_UINT32},
    {"PCM_WRITE_CNT", HISYSEVENT_UINT32},
    {"PCM_WRITE_MAX_INTERVAL", HISYSEVENT_UINT32},
    {"PCM_WRITE_AVG_INTERVAL", HISYSEVENT_UINT32},
    {"PCM_WRITE_GT_FT_CNT", HISYSEVENT_UINT32},
    {"ENCODER_MEM_ALLOC_FAILED_CNT", HISYSEVENT_UINT32},
    {"ENCODER_FAILED_CNT", HISYSEVENT_UINT32},
    {"LEFT_TX_PKT_CNT", HISYSEVENT_UINT32},
    {"LEFT_TX_NO_LINK_DROP_CNT", HISYSEVENT_UINT32},
    {"LEFT_TX_FLUSH_CNT", HISYSEVENT_UINT32},
    {"LEFT_TX_UART_FAILED_CNT", HISYSEVENT_UINT32},
    {"LEFT_TX_FLOW_CTRL_CNT", HISYSEVENT_UINT32},
    {"LEFT_TX_FLOW_CTRL_MAX_PKT_CNT", HISYSEVENT_UINT32},
    {"RIGHT_TX_PKT_CNT", HISYSEVENT_UINT32},
    {"RIGHT_TX_NO_LINK_DROP_CNT", HISYSEVENT_UINT32},
    {"RIGHT_TX_FLUSH_CNT", HISYSEVENT_UINT32},
    {"RIGHT_TX_UART_FAILED_CNT", HISYSEVENT_UINT32},
    {"RIGHT_TX_FLOW_CTRL_CNT", HISYSEVENT_UINT32},
    {"RIGHT_TX_FLOW_CTRL_MAX_PKT_CNT", HISYSEVENT_UINT32},
    {"INTR_EVENT_ENQUEUE_FAILED_CNT", HISYSEVENT_UINT32},
    {"INTR_DATA_ENQUEUE_FAILED_CNT", HISYSEVENT_UINT32},
    {"DATA_INVALID_FORMAT_CNT", HISYSEVENT_UINT32},
    {"BAD_PKT_CNT", HISYSEVENT_UINT32},
    {"INVALID_CONN_HANDLE_CNT", HISYSEVENT_UINT32},
    {"LEFT_DATA_MEM_ALLOC_FAILED_CNT", HISYSEVENT_UINT32},
    {"LEFT_OLD_DATA_DROP_CNT", HISYSEVENT_UINT32},
    {"LEFT_DECODER_FAILED_CNT", HISYSEVENT_UINT32},
    {"LEFT_PCM_SIZE_MISMATCH_CNT", HISYSEVENT_UINT32},
    {"LEFT_DECODED_PCM_DROP_CNT", HISYSEVENT_UINT32},
    {"LEFT_READ_PCM_LOSS_CNT", HISYSEVENT_UINT32},
    {"LEFT_READ_PCM_MISORDER_CNT", HISYSEVENT_UINT32},
    {"RIGHT_DATA_MEM_ALLOC_FAILED_CNT", HISYSEVENT_UINT32},
    {"RIGHT_OLD_DATA_DROP_CNT", HISYSEVENT_UINT32},
    {"RIGHT_DECODER_FAILED_CNT", HISYSEVENT_UINT32},
    {"RIGHT_PCM_SIZE_MISMATCH_CNT", HISYSEVENT_UINT32},
    {"RIGHT_DECODED_PCM_DROP_CNT", HISYSEVENT_UINT32},
    {"RIGHT_READ_PCM_LOSS_CNT", HISYSEVENT_UINT32},
    {"RIGHT_READ_PCM_MISORDER_CNT", HISYSEVENT_UINT32},
    {"BIRATE_UPGRADE_CNT", HISYSEVENT_UINT32},
    {"BITRATE_DOWN_CNT", HISYSEVENT_UINT32},
    {"BITRATE_DOWN_FAILED_CNT", HISYSEVENT_UINT32},
    {"BITRATE_DOWN_FAILED_REASON", HISYSEVENT_STRING},
    {"BITRATE_DOWN_LABEL_FAILED_CNT", HISYSEVENT_UINT32},
    {"CHANNEL_CONT_TIME_24G", HISYSEVENT_STRING},
    {"CHANNEL_CONT_TIME_58G", HISYSEVENT_STRING},
    {"CHANNEL_FREQ_BAND_CHANGE_TIMES", HISYSEVENT_UINT32},
};

/*******************************************************************************
 *  All events, including UE and Excep, are defined here.Note that the sequence is the same as that of DftEventEnum.
 ******************************************************************************/
static DftExcepTypeDB g_dftEventType[DFT_EXCEP_BUTT] = {
    {"", HISYSEVENT_FAULT},  // DFT_EVENT_INVALID
    {"NEARLINK_SWITCH_EXCEPTION", HISYSEVENT_STATISTIC},
    {"NEARLINK_DISCONN_EXCEPTION", HISYSEVENT_FAULT},
    {"NEARLINK_ACCURATESEARCH", HISYSEVENT_FAULT},
    {"NEARLINK_PAIR_EXCEPTION", HISYSEVENT_FAULT},
    {"NEARLINK_UNPAIR_EXCEPTION", HISYSEVENT_STATISTIC},
    {"NEARLINK_MULDEVICE_CONN", HISYSEVENT_STATISTIC},
    {"NEARLINK_STACK_SSAP_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_PAIRING_START_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_PAIRING_CANCEL_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_PAIRING_CFM_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_DIS_EXPOSED_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_DIS_EXPOSED_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_ICCE_CAR_PROFILE_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_ICCE_CAR_PROFILE_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_ICCE_EXPOSED_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_MEASURE_STATE_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_STACK_SM_G_NEGO_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_STACK_SM_T_NEGO_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_STACK_SM_G_AUTH_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_STACK_SM_T_AUTH_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_STACK_SM_ENCP_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_DTFR_CONN", HISYSEVENT_STATISTIC},
    {"NEARLINK_DTFR_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_AUDIO_HEADSET_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_AUDIO_SINK_DEVICE_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_AUDIO_SOURCE_DEVICE_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_AUDIO_MUTE_STREAM_UE", HISYSEVENT_BEHAVIOR},
    {"NEARLINK_AUDIO_STREAM_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_AUDIO_PROFILE_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_DSP_CODEC_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_DSP_CHOPPY_EXCEP", HISYSEVENT_FAULT},
    {"NEARLINK_DSP_STATS", HISYSEVENT_STATISTIC},
};

static DftEventDB g_dftEvent[DFT_EVENT_BUTT] = {
    {"", 0, 1, nullptr},                                // DFT_EVENT_INVALID
    {"NEARLINK_SWITCH_EXCEPTION", SWITCH_KEY_BUTT, SWITCH_PARAM_BUTT, g_switchExcepParam},
    {"NEARLINK_DISCONN_EXCEPTION", DISCONN_KEY_BUTT, DISCONN_PARAM_BUTT, g_disconnExcepParam},
    {"NEARLINK_ACCURATESEARCH", ACCURATESEARCH_KEY_BUTT, ACCURATESEARCH_PARAM_BUTT, g_accuratesearchExcepParam},
    {"NEARLINK_PAIR_EXCEPTION", PAIR_KEY_BUTT, PAIR_PARAM_BUTT, g_pairInfoParam},
    {"NEARLINK_UNPAIR_EXCEPTION", UNPAIR_KEY_BUTT, UNPAIR_PARAM_BUTT, g_unpairInfoParam},
    {"NEARLINK_MULDEVICE_CONN", MULTIDEVICECONN_KEY_BUTT, MULTIDEVICECONN_PARAM_BUTT, g_multideviceconnParam},
    {"NEARLINK_STACK_SSAP_EXCEP", EXCEP_TEMPLATE_THREE_KEY_BUTT, EXCEP_TEMPLATE_THREE_PARAM_BUTT,
        g_templateThreeExcepParam},
    {"NEARLINK_PAIRING_START_UE", UE_TEMPLATE_TWO_KEY_BUTT, UE_TEMPLATE_TWO_PARAM_BUTT, g_templateTwoUeParam},
    {"NEARLINK_PAIRING_CANCEL_UE", UE_TEMPLATE_TWO_KEY_BUTT, UE_TEMPLATE_TWO_PARAM_BUTT, g_templateTwoUeParam},
    {"NEARLINK_PAIRING_CFM_UE", UE_TEMPLATE_TWO_KEY_BUTT, UE_TEMPLATE_TWO_PARAM_BUTT, g_templateTwoUeParam},
    {"NEARLINK_DIS_EXPOSED_EXCEP", EXCEP_TEMPLATE_TWO_KEY_BUTT, EXCEP_TEMPLATE_TWO_PARAM_BUTT, g_disExposedExcepParam},
    {"NEARLINK_DIS_EXPOSED_UE", UE_TEMPLATE_SEVEN_KEY_BUTT, UE_TEMPLATE_SEVEN_PARAM_BUTT, g_disExposedUeParam},
    {"NEARLINK_ICCE_CAR_PROFILE_EXCEP",
        ICCE_PROFILE_EXCEP_KEY_BUTT, ICCE_PROFILE_EXCEP_PARAM_BUTT, g_icceProfileExcepParam},
    {"NEARLINK_ICCE_CAR_PROFILE_UE", UE_TEMPLATE_ONE_KEY_BUTT, UE_TEMPLATE_ONE_PARAM_BUTT, g_templateOneUeParam},
    {"NEARLINK_ICCE_EXPOSED_EXCEP",
        EXCEP_TEMPLATE_ONE_KEY_BUTT, EXCEP_TEMPLATE_ONE_PARAM_BUTT, g_templateOneExcepParam},
    {"NEARLINK_MEASURE_STATE_UE", MEASURE_STATE_KEY_BUTT, MEASURE_STATE_PARAM_BUTT, g_measureStateUeParam},
    {"NEARLINK_STACK_SM_G_NEGO_EXCEP", SM_G_NEGO_KEY_BUTT, SM_G_NEGO_PARAM_BUTT, g_stackSmGNegoExcepParam},
    {"NEARLINK_STACK_SM_T_NEGO_EXCEP", SM_T_NEGO_KEY_BUTT, SM_T_NEGO_PARAM_BUTT, g_stackSmTNegoExcepParam},
    {"NEARLINK_STACK_SM_G_AUTH_EXCEP", SM_G_AUTH_KEY_BUTT, SM_G_AUTH_PARAM_BUTT, g_stackSmGAuthExcepParam},
    {"NEARLINK_STACK_SM_T_AUTH_EXCEP", SM_T_AUTH_KEY_BUTT, SM_T_AUTH_PARAM_BUTT, g_stackSmTAuthExcepParam},
    {"NEARLINK_STACK_SM_ENCP_EXCEP", SM_ENCP_KEY_BUTT, SM_ENCP_PARAM_BUTT, g_stackSmEncpExcepParam},
    {"NEARLINK_DTFR_CONN", DATATRANSFERCONN_KEY_BUTT, DATATRANSFERCONN_PARAM_BUTT, g_datatransferConnParam},
    {"NEARLINK_DTFR_EXCEP", DATATRANSFEREXCEP_KEY_BUTT, DATATRANSFEREXCEP_PARAM_BUTT, g_datatransferExcepParam},
    {"NEARLINK_AUDIO_HEADSET_EXCEP", AUDIO_HEADSET_EXCEP_KEY_BUTT, AUDIO_HEADSET_EXCEP_PARAM_BUTT, 
        g_audioHeadsetExcepParam},
    {"NEARLINK_AUDIO_SINK_DEVICE_UE",
        AUDIO_SINK_DEVICE_KEY_BUTT, AUDIO_SINK_DEVICE_PARAM_BUTT, g_audioSinkDeviceUeParam},
    {"NEARLINK_AUDIO_SOURCE_DEVICE_UE",
        AUDIO_SOURCE_DEVICE_KEY_BUTT, AUDIO_SOURCE_DEVICE_PARAM_BUTT, g_audioSourceDeviceUeParam},
    {"NEARLINK_AUDIO_MUTE_STREAM_UE",
        AUDIO_MUTE_STREAM_KEY_BUTT, AUDIO_MUTE_STREAM_PARAM_BUTT, g_audioMuteStreamUeParam},
    {"NEARLINK_AUDIO_STREAM_EXCEP", STREAM_KEY_BUTT, STREAM_PARAM_BUTT, g_audioStreamExcepParam},
    {"NEARLINK_AUDIO_PROFILE_EXCEP", AUDIO_PROFILE_EXCEP_KEY_BUTT, AUDIO_PROFILE_EXCEP_PARAM_BUTT,
        g_audioProfileExcepParam},
    {"NEARLINK_DSP_CODEC_EXCEPTION", NL_DFT_CODEC_EXCEP_KEY_BUTT, NL_DFT_CODEC_EXCEP_PARAM_BUTT,
        g_audioCodecExcepParam},
    {"NEARLINK_DSP_CHOPPY_EXCEPTION", NL_DFT_CHOPPY_EXCEP_KEY_BUTT, NL_DFT_CHOPPY_EXCEP_PARAM_BUTT,
        g_audioChoppyExcepParam},
    {"NEARLINK_DSP_OFFLOAD_STATS", NL_DFT_STATS_KEY_BUTT, NL_DFT_STATS_PARAM_BUTT, g_audioStatsParam},
    {"", 0, 1, nullptr},                                // DFT_EXCEP_BUTT
    {"STATE_FLOW_INFO", STATE_FLOW_KEY_BUTT, STATE_FLOW_PARAM_BUTT, g_stateFlowParam},
    {"STATE_PEER_INFO", PEER_INFO_KEY_BUTT, PEER_INFO_PARAM_BUTT, g_peerInfoParam},
    {"STATE_CONN_INFO", CONN_INFO_KEY_BUTT, CONN_INFO_PARAM_BUTT, g_connInfoParam},
};

static const std::string EMPTY_STR;

bool IsValidExcep(DftEventEnum eventId)
{
    return eventId > DFT_EVENT_INVALID && eventId < DFT_EXCEP_BUTT;
}

bool IsValidEvent(DftEventEnum eventId)
{
    return eventId > DFT_EVENT_INVALID && eventId < DFT_EVENT_BUTT && eventId != DFT_EXCEP_BUTT;
}

bool IsValidSubEvent(DftEventEnum eventId)
{
    return eventId > DFT_EXCEP_BUTT && eventId < DFT_EVENT_BUTT;
}

bool IsKeyParam(DftEventEnum eventId, int paramId)
{
    return IsValidEvent(eventId) && paramId > 0 && paramId < g_dftEvent[eventId].keyButt;
}

bool IsValidParam(DftEventEnum eventId, int paramId, DftParamType type)
{
    return IsValidEvent(eventId) &&
        paramId > 0 && paramId < g_dftEvent[eventId].paramButt &&
        paramId != g_dftEvent[eventId].keyButt &&
        ConvertToHiSysType(type) == g_dftEvent[eventId].params[paramId].type &&
        type != DFT_PARAM_TYPE_INVALID;
}

bool IsSingleValueType(DftParamType type)
{
    return type > DFT_PARAM_TYPE_INVALID && type < DFT_STRING;
}

bool IsJsonAbleType(DftParamType type)
{
    return type > DFT_PARAM_TYPE_INVALID && type < DFT_SUB_REF;
}

HiSysEventParamType ConvertToHiSysType(DftParamType type)
{
    if (type <= DFT_PARAM_TYPE_INVALID || type >= DFT_TYPE_BUTT) {
        return HISYSEVENT_INVALID;
    }
    return g_dtToHt[type];
}

const char *GetEventName(DftEventEnum eventId)
{
    if (!IsValidEvent(eventId)) {
        return EMPTY_STR.c_str();
    }
    return g_dftEvent[eventId].name;
}

const char *GetParamName(DftEventEnum eventId, int paramId, DftParamType type)
{
    if (!IsValidParam(eventId, paramId, type)) {
        return EMPTY_STR.c_str();
    }
    return g_dftEvent[eventId].params[paramId].name;
}

HiSysEventEventType GetEventType(DftEventEnum eventId)
{
    if (!IsValidExcep(eventId)) {
        return HISYSEVENT_FAULT;
    }
    return g_dftEventType[eventId].eventType;
}

const char *GetDomainName(DftEventEnum eventId)
{
    HiSysEventEventType eventType = g_dftEventType[eventId].eventType;
    switch (eventType) {
        case HISYSEVENT_FAULT:
        case HISYSEVENT_STATISTIC:
        case HISYSEVENT_SECURITY:
            return "NEARLINK_SERVICE";  // 故障/统计/安全事件的域名
        case HISYSEVENT_BEHAVIOR:
            return "NEARLINK_UE";       // 行为事件的域名
    }
}