/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef NLSTK_SLE_ERRCODE_H
#define NLSTK_SLE_ERRCODE_H

// SLE HOST协议栈Error Code，目前暂时和Controller保持一致
typedef enum {
    NLSTK_SLE_SUCCESS = 0x00,
    NLSTK_SLE_UNKNOWN_COMMAND = 0x01,
    NLSTK_SLE_UNKNOWN_CONNECTION_IDENTIFIER = 0x02,
    NLSTK_SLE_HARDWARE_FAILURE = 0x03,
    NLSTK_SLE_AUTHENTICATION_FAILURE = 0x04,
    NLSTK_SLE_PIN_OR_KEY_MISSING = 0x05,
    NLSTK_SLE_MEMORY_CAPACITY_EXCEEDED = 0x06,
    NLSTK_SLE_CONNECTION_TIMEOUT = 0x07,
    NLSTK_SLE_CONNECTION_LIMIT_EXCEEDED = 0x08,
    NLSTK_SLE_SYNC_CONNECTION_LIMIT_EXCEEDED = 0x09,
    NLSTK_SLE_CONNECTION_ALREADY_EXISTS = 0x0A,
    NLSTK_SLE_COMMAND_DISALLOWED = 0x0B,
    NLSTK_SLE_UNACCEPTABLE_BDADDR = 0x0C,
    NLSTK_SLE_COMMAND_TIMEOUT = 0x0D,
    NLSTK_SLE_UNSUPPORTED_REMOTE_FEATURE = 0x0E,
    NLSTK_SLE_INVALID_PARAMETERS = 0x0F,
    NLSTK_SLE_REMOTE_USER_TERMINATED_CONNECTION = 0x10,
    NLSTK_SLE_CONNECTION_TERMINATED_BY_LOCAL_HOST = 0x11,
    NLSTK_SLE_ROLE_CHANGE_NOT_ALLOWED = 0x12,
    NLSTK_SLE_ENCRYPTION_MODE_NOT_ACCEPTABLE = 0x13,
    NLSTK_SLE_LINK_KEY_CANNOT_BE_CHANGED = 0x14,
    NLSTK_SLE_INSTANT_PASSED = 0x15,
    NLSTK_SLE_CHANNEL_CLASSIFICATION_NOT_SUPPORTED = 0x16,
    NLSTK_SLE_INSUFFICIENT_SECURITY = 0x17,
    NLSTK_SLE_ROLE_SWITCH_FAILED = 0x18,
    NLSTK_SLE_CONTROLLER_BUSY = 0x19,
    NLSTK_SLE_ADVERTISING_TIMEOUT = 0x1A,
    NLSTK_SLE_CONNECTION_TERMINATED_MIC_FAILURE = 0x1B,
    NLSTK_SLE_CONNECTION_FAILED_TO_BE_ESTABLISHED = 0x1C,
    NLSTK_SLE_CCA_REJECTED_BUT_ADJUST_USING_CLOCK_DRAGGING = 0x1D,
    NLSTK_SLE_UNKNOWN_ADVERTISING_IDENTIFIER = 0x1E,
    NLSTK_SLE_PACKET_TOO_LONG = 0x1F,
    NLSTK_SLE_UNSPECIFIED_ERROR = 0x20
} NLSTK_DliErrorCode_E;

#endif // NLSTK_SLE_ERRCODE_H