/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef NEARLINK_DFT_DATABASE_AUDIO_H
#define NEARLINK_DFT_DATABASE_AUDIO_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum DftDspCodecExcepParamEnum : int {
    NL_DFT_CODEC_EXCEP_INVALID = 0,
    NL_DFT_CODEC_EXCEP_KEY_BUTT,
    NL_DFT_CODEC_EXCEP_TIME,
    NL_DFT_CODEC_EXCEP_TYPE,
    NL_DFT_CODEC_EXCEP_ALGO,
    NL_DFT_CODEC_EXCEP_ERROR_CODE,
    NL_DFT_CODEC_EXCEP_PARAM_BUTT,
} DftDspCodecExcepParamEnum;

typedef enum DftDspChoppyExcepParamEnum : int {
    NL_DFT_CHOPPY_EXCEP_INVALID = 0,
    NL_DFT_CHOPPY_EXCEP_KEY_BUTT,
    NL_DFT_CHOPPY_EXCEP_TIME,
    NL_DFT_CHOPPY_EXCEP_CNT,
    NL_DFT_CHOPPY_EXCEP_DEVICE_ADDR,
    NL_DFT_CHOPPY_EXCEP_DEVICE_TYPE,
    NL_DFT_CHOPPY_EXCEP_DEVICE_NAME,
    NL_DFT_CHOPPY_EXCEP_REPORT_ADDR,
    NL_DFT_CHOPPY_EXCEP_SCENE_CODE,
    NL_DFT_CHOPPY_EXCEP_SUBSCENE_CODE,
    NL_DFT_CHOPPY_EXCEP_BITRATE_INFO,
    NL_DFT_CHOPPY_EXCEP_CONFIG_PARAM,
    NL_DFT_CHOPPY_EXCEP_FREQ_BAND,
    NL_DFT_CHOPPY_EXCEP_POWER_INFO,
    NL_DFT_CHOPPY_EXCEP_MAC_INFO,
    NL_DFT_CHOPPY_EXCEP_PEER_RSSI,
    NL_DFT_CHOPPY_EXCEP_TXFLUSH_NUM,
    NL_DFT_CHOPPY_EXCEP_ACK_RATE,
    NL_DFT_CHOPPY_EXCEP_CHANNEL_STATUS_24G,
    NL_DFT_CHOPPY_EXCEP_NOISE_AVG_VALUE_24G,
    NL_DFT_CHOPPY_EXCEP_CHANNEL_STATUS_5G,
    NL_DFT_CHOPPY_EXCEP_NOISE_AVG_VALUE_5G,
    NL_DFT_CHOPPY_EXCEP_PARAM_BUTT,
} DftDspChoppyExcepParamEnum;

typedef enum DftDspOffloadStatsParamEnum : int {
    NL_DFT_STATS_INVALID = 0,
    NL_DFT_STATS_KEY_BUTT,
    NL_DFT_STATS_START_TIME,
    NL_DFT_STATS_DURATION,
    NL_DFT_STATS_L2HC_VERSION,
    NL_DFT_STATS_CODEC_TYPE,
    NL_DFT_STATS_SAMPLE_RATE,
    NL_DFT_STATS_BIT_DEPTH,
    NL_DFT_STATS_CHANNEL_MODE,
    NL_DFT_STATS_DEVICE_NUM_IN_COOPERATION_SET,
    NL_DFT_STATS_SDU_INTERVAL,
    NL_DFT_STATS_FLUSH_TIMEOUT,
    NL_DFT_STATS_BURST_NUM,
    NL_DFT_STATS_MAX_DOWN_BITRATE,
    NL_DFT_STATS_MAX_DOWN_BITRATE_DURATION,
    NL_DFT_STATS_PCM_WRITE_CNT,
    NL_DFT_STATS_PCM_WRITE_MAX_INTERVAL,
    NL_DFT_STATS_PCM_WRITE_AVG_INTERVAL,
    NL_DFT_STATS_PCM_WRITE_GT_FT_CNT,
    NL_DFT_STATS_ENCODER_MEM_ALLOC_FAILED_CNT,
    NL_DFT_STATS_ENCODER_FAILED_CNT,
    NL_DFT_STATS_LEFT_TX_PKT_CNT,
    NL_DFT_STATS_LEFT_TX_NO_LINK_DROP_CNT,
    NL_DFT_STATS_LEFT_TX_FLUSH_CNT,
    NL_DFT_STATS_LEFT_TX_UART_FAILED_CNT,
    NL_DFT_STATS_LEFT_TX_FLOW_CTRL_CNT,
    NL_DFT_STATS_LEFT_TX_FLOW_CTRL_MAX_PKT_CNT,
    NL_DFT_STATS_RIGHT_TX_PKT_CNT,
    NL_DFT_STATS_RIGHT_TX_NO_LINK_DROP_CNT,
    NL_DFT_STATS_RIGHT_TX_FLUSH_CNT,
    NL_DFT_STATS_RIGHT_TX_UART_FAILED_CNT,
    NL_DFT_STATS_RIGHT_TX_FLOW_CTRL_CNT,
    NL_DFT_STATS_RIGHT_TX_FLOW_CTRL_MAX_PKT_CNT,
    NL_DFT_STATS_INTR_EVENT_ENQUEUE_FAILED_CNT,
    NL_DFT_STATS_INTR_DATA_ENQUEUE_FAILED_CNT,
    NL_DFT_STATS_DATA_INVALID_FORMAT_CNT,
    NL_DFT_STATS_BAD_PKT_CNT,
    NL_DFT_STATS_INVALID_CONN_HANDLE_CNT,
    NL_DFT_STATS_LEFT_DATA_MEM_ALLOC_FAILED_CNT,
    NL_DFT_STATS_LEFT_OLD_DATA_DROP_CNT,
    NL_DFT_STATS_LEFT_DECODER_FAILED_CNT,
    NL_DFT_STATS_LEFT_PCM_SIZE_NOT_MATCH_CNT,
    NL_DFT_STATS_LEFT_DECODED_PCM_DROP_CNT,
    NL_DFT_STATS_LEFT_READ_PCM_LOSS_CNT,
    NL_DFT_STATS_LEFT_READ_PCM_MISORDER_CNT,
    NL_DFT_STATS_RIGHT_DATA_MEM_ALLOC_FAILED_CNT,
    NL_DFT_STATS_RIGHT_OLD_DATA_DROP_CNT,
    NL_DFT_STATS_RIGHT_DECODER_FAILED_CNT,
    NL_DFT_STATS_RIGHT_PCM_SIZE_NOT_MATCH_CNT,
    NL_DFT_STATS_RIGHT_DECODED_PCM_DROP_CNT,
    NL_DFT_STATS_RIGHT_READ_PCM_LOSS_CNT,
    NL_DFT_STATS_RIGHT_READ_PCM_MISORDER_CNT,
    NL_DFT_STATS_BITRATE_UPGRADE_CNT,
    NL_DFT_STATS_BITRATE_DOWN_CNT,
    NL_DFT_STATS_BITRATE_DOWN_FAILED_CNT,
    NL_DFT_STATS_BITRATE_DOWN_FAILED_REASON,
    NL_DFT_STATS_BITRATE_DOWN_SET_LABEL_FAILED_CNT,
    NL_DFT_STATS_CHANNEL_CONT_TIME_24G,
    NL_DFT_STATS_CHANNEL_CONT_TIME_58G,
    NL_DFT_STATS_CHANNEL_FREQ_BAND_CHANGE_TIMES,
    NL_DFT_STATS_PARAM_BUTT,
} DftDspOffloadStatsParamEnum;

#ifdef __cplusplus
}
#endif

#endif // NEARLINK_DFT_DATABASE_AUDIO_H
