/**
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * @brief        dli命令、事件的操作码
 */
#ifndef DLI_OPCODE_H
#define DLI_OPCODE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    DLI_SUBEVENT_RSSI = 0x01,
    DLI_SUBEVENT_ACB_SUBRATE_CHANGE = 0x2,
    DLI_SUBEVENT_ACB_SUBRATE_REQ = 0x3,
    DLI_SUBEVENT_POWER_LEVEL = 0x13,
} DLI_SubEventOpcode;

typedef enum : uint16_t {
    DLI_CBK_SET_ADV_PARAMS = 0,
    DLI_CBK_SET_ADV_DATA,
    DLI_CBK_ENABLE_ADV,
    DLI_CBK_READ_ADV_DATA_LEN,
    DLI_CBK_READ_ADV_SETS_NUM,
    DLI_CBK_REMOVE_ADV,
    DLI_CBK_ADV_TERMINATED,

    DLI_CBK_SET_SCAN_PARAMS,
    DLI_CBK_ENABLE_SCAN,
    DLI_CBK_SET_SCAN_FILTER,

    DLI_CBK_CONNECT,
    DLI_CBK_CONNECT_CANCEL,
    DLI_CBK_DISCONNECT,
    DLI_CBK_REMOTE_CONNECT_PARAM_REQ,
    DLI_CBK_REMOTE_CONNECT_PARAM_REQ_REPLY,
    DLI_CBK_CONNECT_UPDATE,
    DLI_CBK_ACB_LOW_LATENCY_EN,
    DLI_CBK_SET_MCS,
    DLI_CBK_SET_RX_DATA_FILTER,
    DLI_CBK_READ_REMOTE_RSSI,
    DLI_CBK_READ_REMOTE_FEATURE,
    DLI_CBK_READ_REMOTE_VERSION,
    DLI_CBK_SET_TX_POWER,

    DLI_CBK_READ_ACCESS_FLT_LIST_SIZE,
    DLI_CBK_CLEAR_ACCESS_FLT_LIST,
    DLI_CBK_ADD_DEV_TO_ACCESS_FLT_LIST,
    DLI_CBK_RMV_DEV_FROM_ACCESS_FLT_LIST,
    DLI_CBK_SET_PHY,
    DLI_CBK_SET_ACB_EVT_PARAM,

    DLI_CBK_READ_BUFFER_SIZE,
    DLI_CBK_SET_PUBLIC_ADDRESS,
    DLI_CBK_GET_PUBLIC_ADDRESS,
    DLI_CBK_READ_LOCAL_FEATURE,
    DLI_CBK_READ_LOCAL_VERSION,
    DLI_CBK_SET_HOST_CHANNEL_CLASSIFICATION,
    DLI_CBK_SET_DATA_LEN,
    DLI_CBK_DATA_LEN_CHANGE,
    DLI_CBK_CATCH_CHIP_LOG,
    DLI_CBK_SET_LOCAL_PRIVATE_FEATURE,
    DLI_CBK_READ_REMOTE_PRIVATE_FEATURE,
    DLI_CBK_READ_LOCAL_PRIVATE_FEATURE,

    DLI_CBK_ADV_REPORT,

    DLI_CBK_SEND_CONTROLLER_DATA,
    DLI_CBK_RECV_CONTROLLER_DATA,

    DLI_CBK_ENCRYPT,
    DLI_CBK_RANDOM,
    DLI_CBK_ENCRYPT_PARAM_REQ,
    DLI_CBK_ENCRYPT_PARAM_REQ_REPLY,
    DLI_CBK_ENCRYPT_PARAM_REQ_NEG_REPLY,
    DLI_CBK_READ_SUPPORT_CRYPTO_ALGO,
    DLI_CBK_ENCRYPT_CHANGE,

    DLI_CBK_READ_LOCAL_MEASURE_CAPS,
    DLI_CBK_READ_REMOTE_MEASURE_CAPS,
    DLI_CBK_SET_MEASURE_CONFIG_PARAM,
    DLI_CBK_SET_MEASURE_EN,
    DLI_CBK_MEASURE_IQ_REPORT,
    DLI_CBK_MEASURE_STATE,
    DLI_CBK_RSSI_CHANGE,
    DLI_CBK_POWER_LEVEL_CHANGE,
    // 这两个不再使用
    DLI_CBK_CHIP_RESET_NOTIFY,

    DLI_CBK_SET_5G_FREQ,
    DLI_CBK_SET_5G_TEST_MODE,

    /* 闪链相关 */
    DLI_CBK_SL_CREATE_SMF,
    DLI_CBK_SL_CONFIG_SMF_PARAMS,
    DLI_CBK_SL_WHETHER_ENABLE_SMF,
    DLI_CBK_SL_CONFIG_SMF_DATA,
    DLI_CBK_SL_BIND_SMF_TO_BROADCAST,
    DLI_CBK_SL_BIND_SMF_TO_SCAN,
    DLI_CBK_SL_DESTROY_SMF,

    DLI_CBK_SL_SMF_MANAGE_CHILD_NODE,
    DLI_CBK_SL_CONFIG_SMF_AND_NODE_PRIO,

    DLI_CBK_SL_CREATE_ICB_BROADCAST_NODE,
    DLI_CBK_SL_DESTROY_ICB_BROADCAST_NODE,
    DLI_CBK_SL_CONFIG_ICB_BROADCAST_DATA,
    DLI_CBK_SL_SMF_COMPLETE,
    DLI_CBK_SL_DATA_REPORT,
    DLI_CBK_SL_DATA_SENT_TIMES,

    DLI_CBK_REMOVE_ICG_PARAM,
    DLI_CBK_SET_IOG_PARAM,
    DLI_CBK_IOB_ESTABLISHED,
    DLI_CBK_IOB_REPORT_PARAM,            /* 链路质量参数周期上报 */
    DLI_CBK_IOG_PARAM_UPDATE,            /* 更新同步链路参数事件 */
    DLI_CBK_IOG_LABEL_REPORT,            /* 设置label事件 */
    DLI_CBK_SET_IMG_PARAM,
    DLI_CBK_IMB_ESTABLISHED,
    DLI_CBK_IMB_REPORT_PARAM,            /* 链路质量参数周期上报 */
    DLI_CBK_IMG_PARAM_UPDATE,            /* 更新同步链路参数事件 */
    DLI_CBK_IMG_LABEL_REPORT,            /* 设置label事件 */
    DLI_CBK_REJECT_IOB_REQ,
    DLI_CBK_REJECT_IMB_REQ,
    DLI_CBK_IOB_CONNECT_REQ,
    DLI_CBK_IMB_CONNECT_REQ,

    DLI_CBK_ICB_SETUP_DATA_PATH,
    DLI_CBK_ICB_REMOVE_DATA_PATH,

    DLI_CBK_ENABLE_CONN_HIGH_POWER,
    DLI_CBK_SET_CONN_FRAME_POWER_LEVEL,
    DLI_CBK_ENABLE_FREQ_BAND,
    DLI_CBK_SWITCH_FREQ_BAND,
    DLI_CBK_SET_PEER_DEV_TYPE,
    DLI_CBK_REMOVE_PEER_DEV_TYPE,

    DLI_CBK_ACB_ENABLE_SUBRATE,
    DLI_CBK_ACB_SET_SUBRATE,
    DLI_CBK_ACB_REQ_SUBRATE,

    DLI_CBK_SET_MAC_ID,
    DLI_CBK_GET_MAC_ID,
    DLI_CBK_SET_SLE_DATA_FILTER,
    DLI_CBK_SET_PENCIL_ATTACH_STATE,
    DLI_CBK_SET_POWER_MODE,

    DLI_CBK_QUERY_LINK_QUALITY,

    DLI_CBK_MAX
} DLI_RegOpcode;

typedef enum {
    DLI_CMD_STATUS_EVT = 0x0001,
    DLI_CMD_COMPLETE_EVT = 0x0002,
    DLI_DATA_LENGTH_CHANGE_EVT = 0x0003,
    DLI_ADVERTISING_TERMINATED_EVT = 0x0004,
    DLI_DISCONNECTION_COMPLETE_EVT = 0x0005,
    DLI_REMOTE_CONNECTION_PARAMETER_REQUEST_EVT = 0x0007,
    DLI_NUMBER_OF_COMPLETED_PACKETS_EVT = 0x0009,

    DLI_ENCRYPTION_PARAMETER_REQUEST_EVT = 0x000E,
    DLI_ENCRYPTION_CHANGE_EVT = 0x0011,
    DLI_ACB_LOW_LATENCY_EN_EVT = 0x0013,
    DLI_CONTROLLER_DATA_EVT = 0x0014,

    DLI_IOB_CONNECT_REQ_EVT = 0x0038,
    DLI_IOB_ESTABLISHED_EVT_STD = 0x0039,
    DLI_IOG_LABEL_REPORT_EVT = 0x0061,
    DLI_IOB_ESTABLISHED_EVT = 0x0062,
    DLI_IOG_UPDATE_PARAM_EVT = 0x0063,
    DLI_IOB_PARAM_REPORT_EVT = 0x0064,
    DLI_IMB_CONNECT_REQ_EVT = 0x003A,
    DLI_IMB_ESTABLISHED_EVT_STD = 0x003B,
    DLI_IMG_LABEL_REPORT_EVT = 0x0071,
    DLI_IMB_ESTABLISHED_EVT = 0x0072,
    DLI_IMG_UPDATE_PARAM_EVT = 0x0073,
    DLI_IMB_PARAM_REPORT_EVT = 0x0074,

    DLI_CONNECTION_COMPLETE_EVT = 0x0015,
    DLI_READ_REMOTE_FEATURES_COMPLETE_EVT = 0x0016,
    DLI_READ_REMOTE_VERSION_COMPLETE_EVT = 0x0017,
    DLI_SET_PHY_COMPLETE_EVT = 0x0018,
    DLI_CONNECTION_UPDATE_EVT = 0x0019,
    DLI_ADVERTISING_REPORT_EVT = 0x001A,

    DLI_MEASURE_IQ_REPORT_VENDOR_EVT = 0x004A,
    DLI_READ_REMOTE_MEASURE_CAPS_STATUS_VENDOR_EVT = 0x040F,
    DLI_FREQ_BAND_SWITCH_VENDOR_EVENT = 0x0053,

    // 测量信息上报
    DLI_MEASURE_IQ_REPORT_EVT = 0x0028,
    // 测量状态改变
    DLI_MEASURE_STATE_CHANGE_EVT = 0x0029,
    // 本端测量能力上报
    DLI_READ_LOCAL_MEASURE_CAPS_STATUS_EVT = 0x002B,
    // 对端测量能力上报
    DLI_READ_REMOTE_MEASURE_CAPS_STATUS_EVT = 0x002C,

    DLI_DIS_CONNECTION_COMPLETE_EVT = 0x1405,
    DLI_READ_REMOTE_RSSI_EVT = 0x180C,

    DLI_SET_ACB_EVT_PARAM_EVT = 0x1811,
    DLI_READ_REMOTE_MEASURE_CAPS_EVT = 0x1812,

    DLI_CHIP_RESET_NOTIFY_EVT = 0xFC06,
    DLI_VENDOR_EVENT_EVT = 0xFC07,

    DLI_SET_CONN_FRAME_POWER_LEVEL_EVT = 0xFE01,

    DLI_CMD_ERROR_EVT = 0x00EE,
    DLI_INVALID_EVT = 0xFFFF,
} DLI_EventOpcode;

typedef enum {
    DLI_SET_EVENT_MASK = 0x0401,
    DLI_READ_LOCAL_BUFFER = 0x0402,
    DLI_READ_LOCAL_SUPPORT_FEATS = 0x0403,
    DLI_READ_LOCAL_VERSION_INFORMATION = 0x0404,
    DLI_SET_PUBLIC_ADDRESS = 0x0405,
    DLI_GET_PUBLIC_ADDRESS = 0x0406,
    DLI_RESET = 0x0408,
    DLI_SET_HOST_CHANNEL_CLASSIFICATION = 0x0409,
    DLI_READ_ACCESS_FILTER_LIST_SIZE = 0x040A,
    DLI_CLEAR_ACCESS_FILTER_LIST = 0x040B,
    DLI_ADD_DEVICE_TO_ACCESS_FILTER_LIST = 0x040C,
    DLI_REMOVE_DEVICE_FROM_ACCESS_FILTER_LIST = 0x040D,

    DLI_SET_ADVERTISING_PARAMETERS = 0x0C02,
    DLI_SET_ADVERTISING_DATA = 0x0C03,
    DLI_SET_SCAN_RESPONSE_DATA = 0x0C04,
    DLI_SET_ADVERTISING_ENABLE = 0x0C05,
    DLI_READ_MAXIMUM_ADVERTISING_DATA_LENGTH = 0x0C06,
    DLI_READ_NUMBER_OF_SUPPORTED_ADVERTISING_SETS = 0x0C07,
    DLI_REMOVE_ADVERTISING_SET = 0x0C08,
    DLI_SET_SCAN_PARAMETERS = 0x1001,
    DLI_SET_SCAN_ENABLE = 0x1002,
    DLI_SET_SCAN_DATA = 0x1003,
    DLI_CREATE_CONNECTION = 0x1401,
    DLI_CREATE_CONNECTION_CANCEL = 0x1402,
    DLI_DISCONNECT = 0x1403,
    DLI_READ_REMOTE_FEATURES = 0x1801,
    DLI_READ_REMOTE_VERSION = 0x1802,
    DLI_SET_DATA_LEN = 0x1804,
    DLI_READ_PHY = 0x1805,
    DLI_SET_PHY = 0x1806,
    DLI_CONNECTION_UPDATE = 0x1807,
    DLI_CONNECTION_PARAM_REQ_REPLY = 0x1808,
    DLI_SET_MCS = 0x180A,
    DLI_READ_REMOTER_RSSI = 0x180C,
    DLI_SET_CONTROLLER_DATA = 0x1812,

    DLI_ENCRYPT = 0x1C01,
    DLI_RANDOM = 0x1C02,
    DLI_ENABLE_ENCRYPTION = 0x1C03,
    DLI_DISABLE_ENCRYPTION = 0x1C04,
    DLI_ENCRYPTION_PARAMETER_REQUEST_REPLY = 0x1C05,
    DLI_ENCRYPTION_PARAMETER_REQUEST_NEGATIVE_REPLY = 0x1C06,
    DLI_READ_SUPPORT_CRYPTOGRAPHY_ALGORITHM = 0x1C07,
    DLI_ENABLE_IMG_ENCRYPTION = 0x1C28,

    DLI_READ_LOCAL_MEASURE_CAPS = 0x2001,
    DLI_READ_REMOTE_MEASURE_CAPS = 0x2002,
    DLI_SET_MEASURE_CONFIG_PARAM = 0x2003,
    DLI_SET_MEASURE_EN = 0x2005,

    DLI_SET_IOG_PARAM = 0x2801,
    DLI_SET_IOG_PARAM_TEST = 0x2802,
    DLI_CREATE_IOB = 0x2803,
    DLI_REMOVE_IOG_PARAM = 0x2804,
    DLI_ACCEPT_IOB_REQ = 0x2805,
    DLI_REJECT_IOB_REQ = 0x2806,

    DLI_SET_IMG_PARAM = 0x2807,
    DLI_SET_IMG_PARAM_TEST = 0x2808,
    DLI_CREATE_IMB = 0x2809,
    DLI_REMOVE_IMG_PARAM = 0x280A,
    DLI_ACCEPT_IMB_REQ = 0x280B,
    DLI_REJECT_IMB_REQ = 0x280C,

    DLI_SETUP_ICB_DATA_PATH = 0x280D,
    DLI_REMOVE_ICB_DATA_PATH = 0x280E,
    DLI_TEST_END = 0xFFFF,
} DLI_CmdOpcode;

#ifdef __cplusplus
}
#endif

#endif
