/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/****************************************************************************
 *
 * this file defines dtap module error code.
 *
 ***************************************************************************/

#ifndef DTAP_ERRNO_H
#define DTAP_ERRNO_H

#include "dpfwk_errcode.h"

#define DTAP_SUCCESS 0

typedef enum {
    DTAP_TRANS_RESULT_INTERNAL_FAULT = 1,
    DTAP_TRANS_RESULT_LOGIC_LINK_NOT_FOUND,
    DTAP_TRANS_RESULT_INVALID_DATA,
    DTAP_TRANS_RESULT_CHANNEL_NOT_FOUND,
    DTAP_TRANS_RESULT_EXCEED_MTU_ERR,
    DTAP_TRANS_RESULT_TX_CACHE_FULL,
} DTAP_Trans_Result_t;   // 数据发送结果，和TRANS_Result_t定义保持一致

/* 注册收包回调错误码 */
#define DTAP_REGISTER_RECV_CB_ALLOC_ERR         DP_MAKE_DTAP_TRANS_ERRNO(100)
#define DTAP_REGISTER_RECV_CB_INVALID_PI        DP_MAKE_DTAP_TRANS_ERRNO(101)
#define DTAP_REGISTER_RECV_CB_NULL_ERR          DP_MAKE_DTAP_TRANS_ERRNO(102)
#define DTAP_UNREGISTER_RECV_CB_TCID_NOT_EXIST  DP_MAKE_DTAP_TRANS_ERRNO(103)

/* 传输通道错误码 */
#define DTAP_TRANS_CHANNEL_CREATE_LINK_MAP_ERR DP_MAKE_DTAP_TRANS_ERRNO(200)

/* 传输收发包框架错误码 */
#define DTAP_TRANS_INVALID_DATA         DP_MAKE_DTAP_TRANS_ERRNO(300)
#define DTAP_TRANS_FIND_CHANNEL_ERR     DP_MAKE_DTAP_TRANS_ERRNO(301)
#define DTAP_TRANS_EXCEED_MTU_ERR       DP_MAKE_DTAP_TRANS_ERRNO(302)
#define DTAP_TRANS_INVALID_MODULE_TYPE  DP_MAKE_DTAP_TRANS_ERRNO(303)
#define DTAP_TRANS_MALLOC_ERR           DP_MAKE_DTAP_TRANS_ERRNO(304)
#define DTAP_TRANS_UNSUPPORTED          DP_MAKE_DTAP_TRANS_ERRNO(305)
#define DTAP_TRANS_EXCEED_MAX_ERR       DP_MAKE_DTAP_TRANS_ERRNO(306)
#define DTAP_TRANS_INVALID_PARAM_ERR    DP_MAKE_DTAP_TRANS_ERRNO(307)
#define DTAP_TRANS_CP_POST_ERR          DP_MAKE_DTAP_TRANS_ERRNO(308)
#define DTAP_TRANS_INIT_ERR             DP_MAKE_DTAP_TRANS_ERRNO(309)
#define DTAP_TRANS_ASSIGN_ERR           DP_MAKE_DTAP_TRANS_ERRNO(310)

/* 基础模式错误码 */
#define DTAP_TRANS_BASIC_SEND_EXCEED_MPS    DP_MAKE_DTAP_TRANS_ERRNO(400)
#define DTAP_TRANS_BASIC_SEND_PREPEND_ERR   DP_MAKE_DTAP_TRANS_ERRNO(401)
#define DTAP_TRANS_BASIC_RECV_TRIM_PRE_ERR  DP_MAKE_DTAP_TRANS_ERRNO(402)
#define DTAP_TRANS_BASIC_SEND_GET_CTX_ERR   DP_MAKE_DTAP_TRANS_ERRNO(403)
#define DTAP_TRANS_BASIC_CACHE_OVERFLOW_ERR DP_MAKE_DTAP_TRANS_ERRNO(404)
#define DTAP_TRANS_BASIC_CREATE_FRAME_ERR   DP_MAKE_DTAP_TRANS_ERRNO(405)
/* 透传模式错误码 */
#define DTAP_TRANS_TRANSPARENT_PACK_EXCEED_MPS DP_MAKE_DTAP_TRANS_ERRNO(500)
/* 流模式错误码 */
#define DTAP_TRANS_STREAM_PACK_HEADER_ERR          DP_MAKE_DTAP_TRANS_ERRNO(600)
#define DTAP_TRANS_STREAM_PACK_CRC_ERR             DP_MAKE_DTAP_TRANS_ERRNO(601)
#define DTAP_TRANS_STREAM_TX_FULL                  DP_MAKE_DTAP_TRANS_ERRNO(602)
#define DTAP_TRANS_STREAM_RECV_TRIM_PRE_ERR        DP_MAKE_DTAP_TRANS_ERRNO(603)
#define DTAP_TRANS_STREAM_RECV_TRIM_SUF_ERR        DP_MAKE_DTAP_TRANS_ERRNO(604)
#define DTAP_TRANS_STREAM_RECV_CRC_ERR             DP_MAKE_DTAP_TRANS_ERRNO(605)
#define DTAP_TRANS_STREAM_RECV_DUPLICATED_ERR      DP_MAKE_DTAP_TRANS_ERRNO(606)
#define DTAP_TRANS_STREAM_RX_FULL                  DP_MAKE_DTAP_TRANS_ERRNO(607)
/* 可靠模式错误码 */
#define DTAP_TRANS_RELIABLE_GET_CTX_ERR             DP_MAKE_DTAP_TRANS_ERRNO(700)
#define DTAP_TRANS_RELIABLE_TX_WINDOW_FULL_ERR      DP_MAKE_DTAP_TRANS_ERRNO(701)
#define DTAP_TRANS_RELIABLE_COPY_BUFF_ERR           DP_MAKE_DTAP_TRANS_ERRNO(702)
#define DTAP_TRANS_RELIABLE_FIND_FRAME_ERR          DP_MAKE_DTAP_TRANS_ERRNO(703)
#define DTAP_TRANS_RELIABLE_REACH_MAX_RE_TX_CNT_ERR DP_MAKE_DTAP_TRANS_ERRNO(704)
#define DTAP_TRANS_RELIABLE_COPY_FRAME_ERR          DP_MAKE_DTAP_TRANS_ERRNO(705)
#define DTAP_TRANS_RELIABLE_INVALID_MPS             DP_MAKE_DTAP_TRANS_ERRNO(706)
#define DTAP_TRANS_RELIABLE_FRAGMENT_ERR            DP_MAKE_DTAP_TRANS_ERRNO(707)
#define DTAP_TRANS_RELIABLE_TX_WINDOW_FULL          DP_MAKE_DTAP_TRANS_ERRNO(708)
#define DTAP_TRANS_RELIABLE_TRANS_CHANNEL_FULL      DP_MAKE_DTAP_TRANS_ERRNO(709)
#define DTAP_TRANS_RELIABLE_INVALID_FRAME_NUM       DP_MAKE_DTAP_TRANS_ERRNO(710)

/* 模块初始化错误码 */
#define DTAP_MODULE_DUP_INITED_ERR DP_MAKE_DTAP_TRANS_ERRNO(800)
#define DTAP_MODULE_NOT_INITED_ERR DP_MAKE_DTAP_TRANS_ERRNO(801)

/* 帧模块错误码 */
#define DTAP_FRAME_INVALID_FRAME_TYPE   DP_MAKE_DTAP_FRAME_ERRNO(100)
#define DTAP_FRAME_SEND_ALLOC_ERR       DP_MAKE_DTAP_FRAME_ERRNO(101)
#define DTAP_FRAME_SEND_DLI_SEND_ERR    DP_MAKE_DTAP_FRAME_ERRNO(102)
#define DTAP_FRAME_NULL_PTR_ERR         DP_MAKE_DTAP_FRAME_ERRNO(103)
#define DTAP_FRAME_INVALID_BUFF_LEN     DP_MAKE_DTAP_FRAME_ERRNO(104)
#define DTAP_FRAME_INVALID_EXT_HDR_LEN  DP_MAKE_DTAP_FRAME_ERRNO(105)
#define DTAP_FRAME_INVALID_EXT_LEN      DP_MAKE_DTAP_FRAME_ERRNO(106)
#define DTAP_FRAME_INVALID_EXT_NUM      DP_MAKE_DTAP_FRAME_ERRNO(107)
/* 基础帧错误码 */
#define DTAP_BASIC_FRAME_INVALID_PI_LEN DP_MAKE_DTAP_FRAME_ERRNO(200)
/* 增强帧错误码 */
#define DTAP_ENHANCED_FRAME_HDR_LEN_TOO_SHORT       DP_MAKE_DTAP_FRAME_ERRNO(400)
#define DTAP_ENHANCED_FRAME_LENGTH_TOO_SHORT        DP_MAKE_DTAP_FRAME_ERRNO(401)
#define DTAP_ENHANCED_FRAME_SDU_HDR_LEN_TOO_SHORT   DP_MAKE_DTAP_FRAME_ERRNO(402)
#define DTAP_ENHANCED_FRAME_SDU_LEN_TOO_SHORT       DP_MAKE_DTAP_FRAME_ERRNO(403)
#define DTAP_ENHANCED_FRAME_NOT_SUPPORT_ERR         DP_MAKE_DTAP_FRAME_ERRNO(404)
#define DTAP_ENHANCED_FRAME_PREPEND_ERR             DP_MAKE_DTAP_FRAME_ERRNO(405)
#define DTAP_ENHANCED_FRAME_APPEND_ERR              DP_MAKE_DTAP_FRAME_ERRNO(406)
#define DTAP_ENHANCED_FRAME_BUFF_NEW_ERR            DP_MAKE_DTAP_FRAME_ERRNO(407)
#define DTAP_ENHANCED_FRAME_NULL                    DP_MAKE_DTAP_FRAME_ERRNO(408)
#define DTAP_ENHANCED_FRAME_TRIM_PREFIX_ERR         DP_MAKE_DTAP_FRAME_ERRNO(409)
#define DTAP_ENHANCED_FRAME_TRIM_SUFFIX_ERR         DP_MAKE_DTAP_FRAME_ERRNO(410)
#define DTAP_ENHANCED_FRAME_DUP_FIRST_FRAG_FRAME    DP_MAKE_DTAP_FRAME_ERRNO(411)
#define DTAP_ENHANCED_FRAME_NO_FIRST_FRAG_FRAME     DP_MAKE_DTAP_FRAME_ERRNO(412)
#define DTAP_ENHANCED_FRAME_FRAGMENT_FRAME_LEN_ERR  DP_MAKE_DTAP_FRAME_ERRNO(413)
#define DTAP_ENHANCED_FRAME_UPDATE_FRAG_FRAME_ERR   DP_MAKE_DTAP_FRAME_ERRNO(414)

#endif